app = "booklendiverse"
primary_region = "iad"

[env]
  PORT = "8080"
  NODE_ENV = "production"

[build]
  builder = "heroku/buildpacks:20"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s" 